"""Engine-to-FreeCAD runtime invocation contract metadata."""

from __future__ import annotations

from dataclasses import dataclass

from parametron_freecad.runtime.environment_contract import (
    OPTIONAL_SMOKE_TEST_ENVIRONMENT_VARIABLES,
    PARAMETRON_FREECAD_BIN_ENVIRONMENT_VARIABLE,
    PARAMETRON_FREECAD_STRICT_SMOKE_ENVIRONMENT_VARIABLE,
    REQUIRED_ENGINE_ENVIRONMENT_VARIABLES,
    REQUIRED_RUNTIME_PROCESS_ENVIRONMENT_VARIABLES,
)
from parametron_freecad.runtime.error_contract import (
    ENGINE_ERROR_CONTRACT,
    EngineErrorClassSpec,
    EngineErrorContract,
)
from parametron_freecad.runtime.file_argument_contract import (
    ENGINE_FILE_ARGUMENT_CONTRACT,
    EngineFileArgumentContract,
    FileArgumentSpec,
)
from parametron_freecad.runtime.output_file_contract import (
    ENGINE_OUTPUT_FILE_CONTRACT,
    EngineOutputFileContract,
    OutputFileSpec,
)

ENGINE_INVOCATION_CONTRACT_VERSION = "1.0"
ENGINE_INVOCATION_DISPATCHER = "run_engine_invocation"

SUPPORTED_ENGINE_INVOCATION_MODES = ("execute", "observe")
PLANNED_UNSUPPORTED_ENGINE_INVOCATION_MODES = ("combined",)

COMBINED_INVOCATION_UNSUPPORTED_MESSAGE = (
    "combined execute+observe runtime invocation is not supported"
)

EXECUTION_INVOCATION_FIELD_WORKING_COPY = "working_copy"
EXECUTION_INVOCATION_FIELD_MANIFEST_PATH = "manifest_path"
EXECUTION_INVOCATION_FIELD_RESULT_PATH = "result_path"
EXECUTION_INVOCATION_FIELD_FREECAD_MODULE = "freecad_module"
EXECUTION_INVOCATION_FIELD_RESOLVE_FREECAD_MODULE = "resolve_freecad_module"

EXECUTION_INVOCATION_FIELDS = (
    EXECUTION_INVOCATION_FIELD_WORKING_COPY,
    EXECUTION_INVOCATION_FIELD_MANIFEST_PATH,
    EXECUTION_INVOCATION_FIELD_RESULT_PATH,
    EXECUTION_INVOCATION_FIELD_FREECAD_MODULE,
    EXECUTION_INVOCATION_FIELD_RESOLVE_FREECAD_MODULE,
)

OBSERVATION_INVOCATION_FIELD_DOCUMENT = "document"
OBSERVATION_INVOCATION_FIELD_VERIFICATION_DATA = "verification_data"
OBSERVATION_INVOCATION_FIELD_WORKING_COPY_PATH = "working_copy_path"
OBSERVATION_INVOCATION_FIELD_WORKING_COPY_SHA256 = "working_copy_sha256"
OBSERVATION_INVOCATION_FIELD_OUTPUT_DIRECTORY = "output_directory"

OBSERVATION_INVOCATION_FIELDS = (
    OBSERVATION_INVOCATION_FIELD_DOCUMENT,
    OBSERVATION_INVOCATION_FIELD_VERIFICATION_DATA,
    OBSERVATION_INVOCATION_FIELD_WORKING_COPY_PATH,
    OBSERVATION_INVOCATION_FIELD_WORKING_COPY_SHA256,
    OBSERVATION_INVOCATION_FIELD_OUTPUT_DIRECTORY,
)

ENGINE_RUNTIME_INVOCATION_FIELD_MODE = "mode"
ENGINE_RUNTIME_INVOCATION_FIELD_EXECUTION = "execution"
ENGINE_RUNTIME_INVOCATION_FIELD_OBSERVATION = "observation"

ENGINE_RUNTIME_INVOCATION_FIELDS = (
    ENGINE_RUNTIME_INVOCATION_FIELD_MODE,
    ENGINE_RUNTIME_INVOCATION_FIELD_EXECUTION,
    ENGINE_RUNTIME_INVOCATION_FIELD_OBSERVATION,
)

NEGATIVE_BOUNDARY_NO_COMBINED_EXECUTE_OBSERVE_RUNTIME = (
    "no_combined_execute_observe_runtime"
)
NEGATIVE_BOUNDARY_NO_OBSERVATION_CLI_MODE = "no_observation_cli_mode"
NEGATIVE_BOUNDARY_NO_COMBINED_EXECUTE_OBSERVE_CLI_MODE = (
    "no_combined_execute_observe_cli_mode"
)
NEGATIVE_BOUNDARY_NO_AUTOMATIC_VERIFICATION_FILE_LOADING = (
    "no_automatic_verification_file_loading"
)
NEGATIVE_BOUNDARY_NO_WORKING_COPY_SHA256_COMPUTATION = (
    "no_working_copy_sha256_computation"
)
NEGATIVE_BOUNDARY_NO_COMPONENT_OBSERVATION = "no_component_observation"
NEGATIVE_BOUNDARY_NO_CHECK_EVALUATION = "no_check_evaluation"
NEGATIVE_BOUNDARY_NO_EXPECTED_VS_OBSERVED_COMPARISON = (
    "no_expected_vs_observed_comparison"
)
NEGATIVE_BOUNDARY_NO_VERIFICATION_DECISIONS = "no_verification_decisions"
NEGATIVE_BOUNDARY_NO_GUI_CAPTURE_BEHAVIOR = "no_gui_capture_behavior"
NEGATIVE_BOUNDARY_NO_BROAD_TARGET_RESOLUTION = "no_broad_target_resolution"

ENGINE_INVOCATION_NEGATIVE_BOUNDARIES = (
    NEGATIVE_BOUNDARY_NO_COMBINED_EXECUTE_OBSERVE_RUNTIME,
    NEGATIVE_BOUNDARY_NO_OBSERVATION_CLI_MODE,
    NEGATIVE_BOUNDARY_NO_COMBINED_EXECUTE_OBSERVE_CLI_MODE,
    NEGATIVE_BOUNDARY_NO_AUTOMATIC_VERIFICATION_FILE_LOADING,
    NEGATIVE_BOUNDARY_NO_WORKING_COPY_SHA256_COMPUTATION,
    NEGATIVE_BOUNDARY_NO_COMPONENT_OBSERVATION,
    NEGATIVE_BOUNDARY_NO_CHECK_EVALUATION,
    NEGATIVE_BOUNDARY_NO_EXPECTED_VS_OBSERVED_COMPARISON,
    NEGATIVE_BOUNDARY_NO_VERIFICATION_DECISIONS,
    NEGATIVE_BOUNDARY_NO_GUI_CAPTURE_BEHAVIOR,
    NEGATIVE_BOUNDARY_NO_BROAD_TARGET_RESOLUTION,
)


@dataclass(frozen=True, slots=True)
class EngineInvocationContract:
    """Engine-to-FreeCAD runtime invocation contract metadata."""

    version: str
    dispatcher: str
    supported_modes: tuple[str, ...]
    planned_unsupported_modes: tuple[str, ...]
    combined_invocation_unsupported_message: str
    execution_invocation_fields: tuple[str, ...]
    observation_invocation_fields: tuple[str, ...]
    engine_runtime_invocation_fields: tuple[str, ...]
    negative_boundaries: tuple[str, ...]
    required_engine_environment_variables: tuple[str, ...]
    required_runtime_process_environment_variables: tuple[str, ...]
    optional_smoke_test_environment_variables: tuple[str, ...]
    error_contract: EngineErrorContract
    file_argument_contract: EngineFileArgumentContract
    output_file_contract: EngineOutputFileContract


ENGINE_INVOCATION_CONTRACT = EngineInvocationContract(
    version=ENGINE_INVOCATION_CONTRACT_VERSION,
    dispatcher=ENGINE_INVOCATION_DISPATCHER,
    supported_modes=SUPPORTED_ENGINE_INVOCATION_MODES,
    planned_unsupported_modes=PLANNED_UNSUPPORTED_ENGINE_INVOCATION_MODES,
    combined_invocation_unsupported_message=COMBINED_INVOCATION_UNSUPPORTED_MESSAGE,
    execution_invocation_fields=EXECUTION_INVOCATION_FIELDS,
    observation_invocation_fields=OBSERVATION_INVOCATION_FIELDS,
    engine_runtime_invocation_fields=ENGINE_RUNTIME_INVOCATION_FIELDS,
    negative_boundaries=ENGINE_INVOCATION_NEGATIVE_BOUNDARIES,
    required_engine_environment_variables=REQUIRED_ENGINE_ENVIRONMENT_VARIABLES,
    required_runtime_process_environment_variables=(
        REQUIRED_RUNTIME_PROCESS_ENVIRONMENT_VARIABLES
    ),
    optional_smoke_test_environment_variables=OPTIONAL_SMOKE_TEST_ENVIRONMENT_VARIABLES,
    error_contract=ENGINE_ERROR_CONTRACT,
    file_argument_contract=ENGINE_FILE_ARGUMENT_CONTRACT,
    output_file_contract=ENGINE_OUTPUT_FILE_CONTRACT,
)


__all__ = [
    "COMBINED_INVOCATION_UNSUPPORTED_MESSAGE",
    "ENGINE_FILE_ARGUMENT_CONTRACT",
    "ENGINE_ERROR_CONTRACT",
    "ENGINE_INVOCATION_CONTRACT",
    "ENGINE_INVOCATION_CONTRACT_VERSION",
    "ENGINE_INVOCATION_DISPATCHER",
    "ENGINE_INVOCATION_NEGATIVE_BOUNDARIES",
    "ENGINE_OUTPUT_FILE_CONTRACT",
    "ENGINE_RUNTIME_INVOCATION_FIELDS",
    "ENGINE_RUNTIME_INVOCATION_FIELD_EXECUTION",
    "ENGINE_RUNTIME_INVOCATION_FIELD_MODE",
    "ENGINE_RUNTIME_INVOCATION_FIELD_OBSERVATION",
    "EngineFileArgumentContract",
    "EngineErrorClassSpec",
    "EngineErrorContract",
    "EngineInvocationContract",
    "EngineOutputFileContract",
    "EXECUTION_INVOCATION_FIELDS",
    "EXECUTION_INVOCATION_FIELD_FREECAD_MODULE",
    "EXECUTION_INVOCATION_FIELD_MANIFEST_PATH",
    "EXECUTION_INVOCATION_FIELD_RESOLVE_FREECAD_MODULE",
    "EXECUTION_INVOCATION_FIELD_RESULT_PATH",
    "EXECUTION_INVOCATION_FIELD_WORKING_COPY",
    "FileArgumentSpec",
    "NEGATIVE_BOUNDARY_NO_AUTOMATIC_VERIFICATION_FILE_LOADING",
    "NEGATIVE_BOUNDARY_NO_BROAD_TARGET_RESOLUTION",
    "NEGATIVE_BOUNDARY_NO_CHECK_EVALUATION",
    "NEGATIVE_BOUNDARY_NO_COMBINED_EXECUTE_OBSERVE_CLI_MODE",
    "NEGATIVE_BOUNDARY_NO_COMBINED_EXECUTE_OBSERVE_RUNTIME",
    "NEGATIVE_BOUNDARY_NO_COMPONENT_OBSERVATION",
    "NEGATIVE_BOUNDARY_NO_EXPECTED_VS_OBSERVED_COMPARISON",
    "NEGATIVE_BOUNDARY_NO_GUI_CAPTURE_BEHAVIOR",
    "NEGATIVE_BOUNDARY_NO_OBSERVATION_CLI_MODE",
    "NEGATIVE_BOUNDARY_NO_VERIFICATION_DECISIONS",
    "NEGATIVE_BOUNDARY_NO_WORKING_COPY_SHA256_COMPUTATION",
    "OBSERVATION_INVOCATION_FIELDS",
    "OBSERVATION_INVOCATION_FIELD_DOCUMENT",
    "OBSERVATION_INVOCATION_FIELD_OUTPUT_DIRECTORY",
    "OBSERVATION_INVOCATION_FIELD_VERIFICATION_DATA",
    "OBSERVATION_INVOCATION_FIELD_WORKING_COPY_PATH",
    "OBSERVATION_INVOCATION_FIELD_WORKING_COPY_SHA256",
    "OPTIONAL_SMOKE_TEST_ENVIRONMENT_VARIABLES",
    "OutputFileSpec",
    "PARAMETRON_FREECAD_BIN_ENVIRONMENT_VARIABLE",
    "PARAMETRON_FREECAD_STRICT_SMOKE_ENVIRONMENT_VARIABLE",
    "PLANNED_UNSUPPORTED_ENGINE_INVOCATION_MODES",
    "REQUIRED_ENGINE_ENVIRONMENT_VARIABLES",
    "REQUIRED_RUNTIME_PROCESS_ENVIRONMENT_VARIABLES",
    "SUPPORTED_ENGINE_INVOCATION_MODES",
]
